genetic_algorithm:
  population_size: 70
  generations: 50
  mutation_probability: 0.4
  crossover_probability: 0.4

acceptance_criteria:
  bias_error_threshold: 5  # Bias error threshold in percent for all end uses
  abs_error_elec_threshold: 500  # Absolute error threshold for electricity in kWh
  abs_error_fuel_threshold: 5  # Absolute error threshold for fossil fuels in MBtu

value_choices:
  misc_load_multiplier_choices: [0.5, 0.75, 1, 1.5, 2]
  air_leakage_multiplier_choices: [0.75, 1, 1.5]
  heating_efficiency_multiplier_choices: [0.9, 1, 1.1]
  cooling_efficiency_multiplier_choices: [0.9, 1, 1.1]
  roof_r_value_multiplier_choices: [0.9, 1, 1.1]
  ceiling_r_value_multiplier_choices: [0.9, 1, 1.1]
  above_ground_walls_r_value_multiplier_choices: [0.9, 1, 1.1]
  below_ground_walls_r_value_multiplier_choices: [0.9, 1, 1.1]
  slab_r_value_multiplier_choices: [0.9, 1, 1.1]
  floor_r_value_multiplier_choices: [0.9, 1, 1.1]
  heating_setpoint_offset_choices: [-2, 0, 2]
  cooling_setpoint_offset_choices: [-2, 0, 2]
  water_heater_efficiency_multiplier_choices: [0.9, 1, 1.1]
  water_fixtures_usage_multiplier_choices: [0.5, 0.75, 1, 1.5, 2]
  window_u_factor_multiplier_choices: [0.9, 1, 1.1]
  window_shgc_multiplier_choices: [0.9, 1, 1.1]
  appliance_usage_multiplier_choices: [0.5, 0.75, 1, 1.5, 2]
  lighting_load_multiplier_choices: [0.5, 0.75, 1, 1.5, 2]

utility_bill_criteria:
  min_days_of_consumption_data: 330
  max_years: 25
  min_electrical_bill_days: 20
  max_electrical_bill_days: 45
  min_num_electrical_bills: 10
