genetic_algorithm:
  population_size: 70
  generations: 50
  mutation_probability: 0.4
  crossover_probability: 0.4

acceptance_criteria:
  bias_error_threshold: 5  # Bias error threshold in percent for all end uses
  abs_error_elec_threshold: 500  # Absolute error threshold for electricity in kWh
  abs_error_fuel_threshold: 5  # Absolute error threshold for fossil fuels in MBtu

value_choices:
  misc_load_multiplier_choices: [0.1, 0.25, 0.5, 0.75, 0.9, 1, 1.1, 1.25, 1.5, 2, 4, 7, 10]
  air_leakage_multiplier_choices: [0.5, 0.75, 0.9, 1, 1.1, 1.25, 1.5, 2]
  hvac_eff_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  roof_r_value_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  ceiling_r_value_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  above_ground_walls_r_value_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  below_ground_walls_r_value_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  slab_r_value_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  floor_r_value_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  heating_setpoint_choices: [-5, -3, -1, 0, 1, 3, 5]
  cooling_setpoint_choices: [-5, -3, -1, 0, 1, 3, 5]
  water_heater_efficiency_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  water_fixtures_usage_multiplier_choices: [0.1, 0.25, 0.5, 0.75, 0.9, 1, 1.1, 1.25, 1.5, 2, 4, 7, 10]
  window_u_factor_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  window_shgc_multiplier_choices: [0.8, 0.9, 1, 1.1, 1.2]
  appliance_usage_multiplier_choices: [0.1, 0.25, 0.5, 0.75, 0.9, 1, 1.1, 1.25, 1.5, 2, 4, 7, 10]
  lighting_load_multiplier_choices: [0.1, 0.25, 0.5, 0.75, 0.9, 1, 1.1, 1.25, 1.5, 2, 4, 7, 10]

min_days_of_consumption_data: 330
max_years: 25
min_electrical_bill_days: 20
max_electrical_bill_days: 45
min_num_electrical_bills: 10
