genetic_algorithm:
  population_size: 70
  generations: 100
  mutation_probability: 0.4
  crossover_probability: 0.4

value_choices:
  plug_load_pct_choices: [-0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 5, 10]
  air_leakage_pct_choices: [-0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  hvac_eff_pct_choices: [-0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5]
  r_value_pct_choices: [-0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 5, 10]
  heating_setpoint_choices: [-9, -7, -5, -3, -1, 0, 1, 3, 5, 7, 9]
  cooling_setpoint_choices: [-9, -7, -5, -2, -1, 0, 1, 3, 5, 7, 9]
