[project]
name = "openstudio-hpxml-calibration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noel Merket", email = "noel.merket@nrel.gov" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
openstudio-hpxml-calibration = "openstudio_hpxml_calibration:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
