name: CI

on:
  push:

# Cancel in-progress jobs when a new commit is pushed to the PR
# This avoids CI jobs "stacking up" for the same PR
# This won't stop existing job if new commit is pushed with [ci skip].
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  OS_VERSION: "3.10.0"
  OS_SHA: 86d7e215a1

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the package & dependencies
        run: |
          uv version
          uv sync

      - name: Lint & format
        run: uv run pre-commit run --all-files

      - name: Install OpenStudio on Linux
        if: runner.os == 'Linux'
        run: |
          wget -q -O OpenStudio.deb https://github.com/NREL/OpenStudio/releases/download/v${OS_VERSION}/OpenStudio-${OS_VERSION}+${OS_SHA}-Ubuntu-24.04-x86_64.deb
          sudo dpkg -i OpenStudio.deb
          rm OpenStudio.deb

      - name: Install OpenStudio on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Download the tarball in the runner temp directory
          $DownloadPath = Join-Path $env:RUNNER_TEMP "Windows.tar.gz"
          Invoke-WebRequest -OutFile $DownloadPath -URI "https://github.com/NREL/OpenStudio/releases/download/v${env:OS_VERSION}/OpenStudio-${env:OS_VERSION}+${env:OS_SHA}-Windows.tar.gz"

          # Extract the tarball in the runner temp directory
          $ExtractPath = Join-Path $env:RUNNER_TEMP "OpenStudio-${env:OS_VERSION}+${env:OS_SHA}-Windows"
          tar -xzf $DownloadPath -C $env:RUNNER_TEMP

          # Add the bin directory to PATH
          $OpenStudioBinPath = Join-Path $ExtractPath "bin"
          echo $OpenStudioBinPath >> $env:GITHUB_PATH

      - name: Download Weather
        run: uv run openstudio-hpxml-calibration download-weather

      - name: Measure unit tests
        run: |
          cd src/measures/ModifyXML/tests
          openstudio modify_xml_test.rb

      - name: Unit tests
        run: uv run pytest -v

      - name: Save test results
        uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Linux' && matrix.python-version == '3.13' }}
        with:
          name: test_results
          path: tests/results/*

      - name: Calibrate test files
        if: ${{ runner.os == 'Linux' && matrix.python-version == '3.13' }}
        run: |
          skip_filenames=(
            "ihmh6"                 # Missing natural gas consumption data
            "ihmh7"                 # Has PV
            "house02"               # Missing natural gas consumption data
            "house05"               # Missing natural gas consumption data
            "house06"               # Billing period longer than 45 days
            "house07"               # Billing period longer than 45 days
            "house09"               # Missing natural gas consumption data
            "house10"               # Missing natural gas consumption data
            "house14"               # Billing period shorter than 20 days
            "house17"               # Billing period shorter than 20 days
            "house22"               # Gap in electricity consumption data
            "house31"               # Gap in electricity consumption data
            "house32"               # Electricity consumption covers less than 300 days
            "house37"               # Electricity consumption covers less than 300 days
            "house43"               # Billing period shorter than 20 days
            "house44"               # Missing electricity consumption data
            "house45"               # Missing electricity consumption data
            "house46"               # Zeroes in electricity consumption data
            "house48"               # Billing period shorter than 20 days
            "house49"               # Billing period shorter than 20 days
            "house50"               # Billing period shorter than 20 days
            "house57"               # Natural gas consumption covers less than 300 days
            "house77"               # Billing period shorter than 20 days
            "house83"               # Natural gas consumption covers less than 300 days
            "house85"               # Missing fuel oil consumption data
            "house86"               # Missing fuel oil consumption data
            "house90"               # Billing period shorter than 20 days
          )
          for xml in test_hpxmls/**/*.xml; do
            if [[ $xml == *"invalid_homes"* ]]; then
              continue
            fi
            base_xml=$(basename "$xml" .xml)
            if [[ " ${skip_filenames[*]} " =~ " ${base_xml} " ]]; then
              continue
            fi
            output_dir=tests/all_calibration_results/$base_xml
            # TODO: Add --save-all-results
            uv run openstudio-hpxml-calibration calibrate --hpxml-filepath $xml --config-filepath tests/data/test_config.yaml --output-dir $output_dir --verbose
          done

      - name: Save calibration results
        uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Linux' && matrix.python-version == '3.13' }}
        with:
          name: calibration_results
          path: tests/all_calibration_results/*
